### ISSUE TITLE
Setting Up a buf.build Organization Account for Protobuf API 

### ISSUE THREAD

**Issue by D4ryl00** [gnolang/gnomobile#53]
Our team is ready to push our API on the [buf.build](https://buf.build/) registry.

To do that, a Gno organization account should be created. Then, our Berty user accounts should have enough privileges to push commits in a Gnomobile repository.

**Comment by moul** [comment]
Should be good. Can you try?

**Comment by D4ryl00** [comment]
I don't have enough permission to create a new repository, I think that should be done by an owner. @moul, can you do this for me?
<img width="665" alt="image" src="https://github.com/gnolang/gnomobile/assets/13605410/197ab866-a4f7-48ae-ae80-fc1c3c8cc167">

**Comment by jefft0** [comment]
@D4ryl00 says "I was able to create the gnomobile repo: https://buf.build/gnolang/gnomobile ".

**Comment by jefft0** [comment]
@D4ryl00 now has the admin role. Close.
